config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show, :create, :new] do
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create]
      end
   end

   root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comment
  has_many :like
  belongs_to :author, class_name: 'User'
  after_save :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def return_recent_comments
    comment.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :post, foreign_key: 'author_id'
  has_many :comment, foreign_key: 'author_id'
  has_many :like, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    post.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = Comment.new(comment_params)
    comment.author = current_user
    comment.post = post
    if comment.save
      flash[:success] = 'Comment created successfully'
    else
      flash[:error] = 'Comment not created'
    end
    redirect_to user_post_path(current_user, post)
  end

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    like = Like.new
    like.author = current_user
    like.post = post
    if like.save
      flash[:success] = 'Like created successfully'
    else
      flash[:error] = 'Like not created'
    end
    redirect_to user_post_path(current_user, post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author: @user)
  end

  def show
    puts params
    @post = Post.find(params[:id])
  end

  # form actions
  def new
    @user = User.find(current_user.id)
    @post = @user.post.new
    render :new, locals: { post: @post }
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.post.new(post_params)
    respond_to do |format|
      format.html do
        if @post.save
          flash[:success] = 'Post created successfully'
          redirect_to "#{user_posts_path(@user)}/#{@post.id}"
        else
          flash[:error] = 'Post not created'
          render :new, locals: { post: @post }
        end
      end
    end
  end

  private

  def post_params
    params.require(:new_post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Add Comment</h1>
<%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, scope: :comment, class: "form" do |form| %>
  <div class="form-input">
    <%= form.label :text %>
    <%= form.text_area :text, class: "form-text" %>
  </div>
  <div class="form-submit">
       <%= form.submit "Add Comment" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/simpledotcss@2.0.0/simple-v1.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_comment.html.erb
<% comment.each do |coment| %>
<div class="comment">
    <div class="comment-list">
      <%= coment.author.name %>
    </div>
    <div class="comment-text">
      <%= coment.text %>
    </div>
</div>
<%end%>

app/views/partials/_post.html.erb
<li>
 <h3> <% post.title%> </h3>
 <p> <%= truncate(post.text, :length => 150) %> </p>
 <strong>
  <p class="placeholder stats">
   Comments: <%= post.comments_counter %>,
   Likes: <%= post.likes_counter %> </p>
 </strong>
</li>

app/views/partials/_user.html.erb
<div class='user-card'>
   <div class="user_photo">
    <img src=<%= user.photo %> alt="picture of <%= user.name%>" />
  </div>
  <div class="user-info">
    <h3><%= user.name %></h3>
    <p class="placeholder">Number of Posts: <%= user.posts_counter%> </p>
   </div>
</div>

app/views/posts/index.html.erb
<h1>List of all Posts by <%= @user.name%></h1>
<section >
  <%= render'partials/user', user: @user %>
    <% @posts.each do |post| %>
   <a href="/users/<%= @user.id %>/posts/<%= post.id %>">
    <ul class="post-list">
    <%= render 'partials/post', post: post %>
    </ul>
    <ul class="comments-list">
      <% if post.comments_counter > 0 %>
            <%= render 'partials/comment', comment: post.return_recent_comments %>
      <% else %>
        <li>No comments</li>
      <% end %>
    </ul>
   <a>
    <% end %>

  <button type='button'>Pagination</button>
</section>

app/views/posts/new.html.erb
<h1>Create Post</h1>
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :new_post do |form| %>
  <div class="form-input">
    <%= form.label :Subject %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-input">
    <%= form.label :Text %>
    <%= form.text_area :text, class: "form-control text" %>
  </div>
    <%= form.submit %>
 
<% end %>

app/views/posts/show.html.erb
<div class="posts">
  <div class="card-info">
    <h3> <%=@post.title%> by <%= @post.author.name%> </h3>
    <p> <%= @post.text%> </p>
    <p class="placeholder stats placeholder-top"> Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %> </p>
  </div>
  <div class="card-info">
    <% @post.comment.each do |coment| %>
      <p> <%= coment.author.name%>: <%= coment.text%><p>
    <% end %>  
    <%= form_with url: "/users/#{@post.author_id}/posts/#{@post.id}/likes" do |f| %>
  <%= f.submit "Like" %>
   <a href="<%=@post.id%>/comments/new"><button class="btn">Comment</button></a>
  <% end %>
 
  </div>
</div>

app/views/users/index.html.erb
<h1>List of all Users</h1>
<ul class='users_list'>
<% @users.each do |user| %>
 <a href='/users/<%= user.id %>'>
    <%= render 'partials/user', user: user %>
 <a>
<% end %>
</ul>

app/views/users/show.html.erb
<h1>User Details</h1>
<div class="user">
<%= render 'partials/user', user: @user %>
<div class='bio'>
<p><%= @user.bio %></p>
</div>
<h5>Recent posts</h5>
<ul class='card'>
    <% @user.recent_posts.each do |post| %>
      <a href="/users/<%= @user.id %>/posts/<%= post.id %> ">
        <%= render 'partials/post', post: post %>
      </a>
    <% end %>
</ul>
<a href="/users/<%= @user.id %>/posts">
        <button> See all Posts </button>
      </a>
</div>